# ===========================================================================
# Project:   ChanceTest
# Copyright: ©2011 My Company, Inc.
# ===========================================================================

# This is your Buildfile for your app, ChanceTest. This tells SproutCore
# how to build your app. These settings override those in your project
# Buildfile, which contains default settings for all apps in your project.
#
# This line tells SproutCore's CSS preprocessor what class names to target.
# Since your app has a theme named 'chance-test', and it is based on SproutCore's
# Ace theme (named 'ace'), it is set to 'ace.chance-test'.
config :chance_test, :css_theme => 'ace.chance-test'

