# needed for HTML test...
config :html_test, 
  :required => [:req_target_2],
  :layout   => 'lib/layout_template.rhtml',
  :debug_required => [:debug],
  :test_required  => [:qunit]
  
config :req_target_2, :required => [:req_target_1]

config :test_test,
  :test_layout   => 'lib/test_layout.rhtml',
  :debug_required => [:debug],
  :test_required  => [:qunit],
  :theme => nil

config :bundle_test,
  :required => [:req_target_1],
  :dynamic_required => [:req_target_2]