config :req_target_2, :required => [:req_target_1]
#
# needed for HTML test...
config :html_test,
  :required => ['/req_target_2'],
  :layout   => 'lib/layout_template.rhtml',
  :debug_required => [:debug],
  :test_required  => [:qunit]

config :test_test,
  :test_layout   => 'lib/test_layout.rhtml',
  :debug_required => [:debug],
  :test_required  => [:qunit],
  :theme => nil

config '/module_test/deferred_module',
  :required => [:required_target, '/module_test/dynamic_req_target_1']

config :module_test,
  :deferred_modules => [:deferred_module],
  :prefetched_modules => [:required_target],
  :inlined_modules => [:inlined_module]
