# needed for HTML test...
config :html_test, 
  :required => [:req_target_2],
  :layout   => 'lib/layout_template.rhtml'
  
config :req_target_2, :required => [:req_target_1]

config :test_test,
  :test_layout   => 'lib/test_layout.rhtml'
  