# Framework-level Buildfile

# By default, all of these frameworks don't require anything. 
# This is necessary since the default buildfile requires sproutcore.
config :all, :required => [] 

config :sproutcore, :required => :desktop

config :foundation,
  :required => :costello
  
config :application, 
  :required => %w(costello foundation)
  
config :data_store,
  :required => %w(costello foundation)
  
config :desktop,
  :required => %w(costello foundation application data_store)
  
config :mobile,
  :required => %w(costello foundation application data_store)

%w(uploader test_runner).each do |target_name|
  config target_name, :required => :sproutcore
end
