# Sample buildfile.  Just define a test task to ensure the buildfile loads 
# properly. 

# Set the global RESULTS constant this way to avoid warnings during testing.
# Normally a Buildfile should only be loaded one time so you won't need to 
# use this method.
Kernel.const_reset :RESULTS, {}

task :default => :test_task1

task :test_task1 do
 RESULTS[:test_task1] = true
end

# Test importing a file...
import File.join(File.dirname(__FILE__), "task_module.rake")
