# Sample buildfile.  Just define a test task to ensure the buildfile loads 
# properly. 

task :default => :test_task1

task :test_task1 do
 RESULTS[:test_task1] = true
end

# Test importing a file...
import File.join(File.dirname(__FILE__), "task_module.rake")
